name: scrape

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Allow using custom token for push

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          PYTHONUNBUFFERED: '1'
        run: python scrape_ollama.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "✨ Data update at $(date -u '+%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
